### ISSUE TITLE
Unable to get dict.json & tx-calldata.json from IPFS CID

### ISSUE THREAD

**Issue by 1xAhmed** [1inch/calldata-compressor#16]
@zZoMROT  @ZumZoom @byshape  @SevenSwen Hey guys, first of all, apologies for tagging y'all like this.

Secondly, could anyone please help me as I am unable to get the hosted data required to test this repo? **Maybe create public gist for these files or something else.**

You hosted some test data files on IPFS and I am unable to get it. Could someone please help me? I am stuck and I really need this to proceed further.

  IPFS CID 
 dict.json
 Qmb4fEEdQe9QB4ChBFK8bJVkefCjG4nB91hgQ2kcKsKGWK

tx-calldata.json  
QmQnjk5MKMiC6jZNjWgXKkbCMFFznNYaHRsS281jV94wpe 

I tried alot of gateways, but none of them gives the file

https://ipfs.io/ipfs/Qmb4fEEdQe9QB4ChBFK8bJVkefCjG4nB91hgQ2kcKsKGWK

https://ipfs.io/ipfs/QmQnjk5MKMiC6jZNjWgXKkbCMFFznNYaHRsS281jV94wpe

**Comment by zZoMROT** [comment]
Thank you for highlighting the issue!

The repository has been updated, and the example files are now available via Git LFS. These files should automatically download when you pull or clone the repository.

If they don’t download by default, you can use the following command to fetch them:
```
git lfs pull
```

Feel free to reach out if you have any further questions. Always happy to help! 😊
